#!/usr/bin/env python3
# pi_inference.py - Standalone PatchCore inference for Raspberry Pi
# Generated by deploy_to_pi.py
# This script runs WITHOUT Anomalib - only needs PyTorch + OpenCV

import torch
import torch.nn as nn
import numpy as np
from pathlib import Path
from PIL import Image
import csv
import argparse
from datetime import datetime

# Image transformations (matching training)
from torchvision.transforms.v2 import Compose, Resize, ToImage, ToDtype, Normalize

class PatchCoreInference:
    """Standalone PatchCore inference engine"""

    def __init__(self, checkpoint_path, device='cpu'):
        """
        Initialize inference engine

        Args:
            checkpoint_path: Path to patchcore_pi.pth
            device: 'cpu' or 'cuda'
        """
        self.device = torch.device(device)
        self.image_size = (512, 512)
        self.checkpoint_path = Path(checkpoint_path)

        print(f"Initializing PatchCore Inference")
        print(f"  Device: {self.device}")
        print(f"  Image size: {self.image_size}")
        print(f"  Checkpoint: {self.checkpoint_path}")

        # Load checkpoint
        self._load_checkpoint()

        # Setup transforms
        self._setup_transforms()

        # Load backbone
        self._load_backbone()

        print("✅ Initialization complete\n")

    def _load_checkpoint(self):
        """Load model checkpoint"""
        checkpoint = torch.load(self.checkpoint_path, map_location=self.device)

        self.state_dict = checkpoint['model_state_dict']
        self.memory_bank = checkpoint.get('memory_bank')
        self.backbone_name = checkpoint.get('backbone', 'resnet18')

        if self.memory_bank is not None:
            if isinstance(self.memory_bank, torch.Tensor):
                self.memory_bank = self.memory_bank.to(self.device)
                print(f"  Memory bank loaded: {self.memory_bank.shape}")
            else:
                print("  ⚠️  Memory bank not found in checkpoint")
                self.memory_bank = None
        else:
            print("  ⚠️  No memory bank in checkpoint")

    def _setup_transforms(self):
        """Setup image preprocessing"""
        self.transform = Compose([
            Resize(self.image_size),
            ToImage(),
            ToDtype(torch.float32, scale=True),
            Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])

    def _load_backbone(self):
        """Load ResNet18 backbone"""
        from torchvision.models import resnet18

        # Load pretrained ResNet18
        self.backbone = resnet18(pretrained=False)

        # Load trained weights
        # Filter only backbone weights from state_dict
        backbone_state = {}
        for key, value in self.state_dict.items():
            if 'feature_extractor' in key or 'model.feature_extractor' in key:
                # Remove prefix to match torchvision ResNet
                new_key = key.replace('feature_extractor.', '').replace('model.feature_extractor.', '')
                backbone_state[new_key] = value

        if backbone_state:
            self.backbone.load_state_dict(backbone_state, strict=False)
            print(f"  Loaded backbone weights: {len(backbone_state)} layers")
        else:
            print("  ⚠️  Using pretrained ImageNet weights")

        self.backbone = self.backbone.to(self.device)
        self.backbone.eval()

        # Setup feature extraction hooks
        self.features = {}

        def hook_fn(name):
            def hook(module, input, output):
                self.features[name] = output
            return hook

        # Register hooks for layer2 and layer3
        self.backbone.layer2.register_forward_hook(hook_fn('layer2'))
        self.backbone.layer3.register_forward_hook(hook_fn('layer3'))

    def predict(self, image_path):
        """
        Run inference on single image

        Args:
            image_path: Path to image file

        Returns:
            dict with 'score' and 'prediction'
        """
        # Load and preprocess image
        image = Image.open(image_path).convert('RGB')
        image_tensor = self.transform(image).unsqueeze(0).to(self.device)

        # Extract features
        with torch.no_grad():
            _ = self.backbone(image_tensor)

            # Concatenate features from layer2 and layer3
            features = []
            for layer_name in ['layer2', 'layer3']:
                if layer_name in self.features:
                    feat = self.features[layer_name]
                    # Adaptive pooling to consistent size
                    feat = nn.functional.adaptive_avg_pool2d(feat, (1, 1))
                    feat = feat.flatten(1)
                    features.append(feat)

            if not features:
                return {'score': 0.5, 'prediction': 'unknown'}

            # Concatenate all features
            embedding = torch.cat(features, dim=1)  # Shape: [1, feature_dim]

            # Calculate anomaly score using memory bank
            if self.memory_bank is not None:
                # Compute distances to all memory bank samples
                distances = torch.cdist(embedding, self.memory_bank)  # [1, N]

                # Get k nearest neighbors (k=9 as in training)
                k = min(9, self.memory_bank.shape[0])
                knn_distances, _ = torch.topk(distances, k, largest=False, dim=1)

                # Anomaly score is mean of k-NN distances
                anomaly_score = knn_distances.mean().item()
            else:
                # Fallback: random score
                anomaly_score = 0.5

            return {
                'score': anomaly_score,
                'prediction': 'defective' if anomaly_score > 0.95 else 'normal'
            }

    def process_folder(self, input_folder, output_csv, threshold=0.95):
        """
        Process all images in folder and save results to CSV

        Args:
            input_folder: Path to folder containing images
            output_csv: Path to output CSV file
            threshold: Anomaly score threshold for defect detection
        """
        input_path = Path(input_folder)

        if not input_path.exists():
            print(f"❌ Input folder not found: {input_path}")
            return

        # Find all images
        image_files = []
        for ext in ['*.jpg', '*.jpeg', '*.png', '*.bmp']:
            image_files.extend(input_path.rglob(ext))

        image_files = sorted(image_files)

        if not image_files:
            print(f"❌ No images found in {input_path}")
            return

        print(f"\n📂 Processing {len(image_files)} images from: {input_path}")
        print(f"💾 Output CSV: {output_csv}")
        print(f"🎯 Threshold: {threshold}\n")

        # Process images
        results = []

        for img_path in image_files:
            try:
                result = self.predict(img_path)

                results.append({
                    'filename': img_path.name,
                    'score': result['score'],
                    'predicted_label': 'defective' if result['score'] > threshold else 'normal',
                    'path': str(img_path.relative_to(input_path))
                })

                print(f"  {img_path.name:40s} | Score: {result['score']:.4f} | {result['prediction']:10s}")

            except Exception as e:
                print(f"  ❌ Error processing {img_path.name}: {e}")

        # Save to CSV
        output_path = Path(output_csv)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['filename', 'score', 'predicted_label', 'path'])
            writer.writeheader()
            writer.writerows(sorted(results, key=lambda x: x['score'], reverse=True))

        print(f"\n✅ Results saved to: {output_path}")

        # Print summary
        normal_count = sum(1 for r in results if r['predicted_label'] == 'normal')
        defective_count = len(results) - normal_count

        print(f"\n📊 Summary:")
        print(f"   Total images: {len(results)}")
        print(f"   Normal: {normal_count} ({normal_count/len(results)*100:.1f}%)")
        print(f"   Defective: {defective_count} ({defective_count/len(results)*100:.1f}%)")

def main():
    parser = argparse.ArgumentParser(description='PatchCore Inference for Raspberry Pi')
    parser.add_argument('--input', required=True, help='Input folder containing images')
    parser.add_argument('--output', default='detailed_result.csv', help='Output CSV file')
    parser.add_argument('--checkpoint', default='pi_deployment/patchcore_pi.pth', help='Model checkpoint file')
    parser.add_argument('--threshold', type=float, default=0.95, help='Anomaly score threshold')
    parser.add_argument('--device', default='cpu', help='Device: cpu or cuda')

    args = parser.parse_args()

    print("="*60)
    print("PatchCore Inference - Raspberry Pi")
    print("="*60)

    # Initialize inference engine
    inference = PatchCoreInference(args.checkpoint, device=args.device)

    # Process images
    inference.process_folder(args.input, args.output, threshold=args.threshold)

    print("\n✅ Inference complete!")

if __name__ == "__main__":
    main()
